### ISSUE TITLE
Let define syntax for extensions

### ISSUE THREAD

**Issue by isqua** [csscomb/core#6]
E.g.

```
{
  ".css": "less",
  ".pcss": "scss"
}
```

It will be useful when I using PostCSS with some plugins, that extend CSS syntax. I use `postcss-nested` and get an error when try to csscomb the file:

``` less
.header
{
    color: #fff;
    background-color: $darkGray;

    .wrapper {
        display: flex;
        flex-direction: column;

        @media (--tablet)
        {
            flex-direction: row;
        }
    }
}
```

the error:

```
Please check the validity of the block starting from line #6

4 |     background-color: $darkGray;
6*|     .wrapper {
7 |         display: flex;
8 |         flex-direction: column;
```
